console.log(document.getElementsByTagName("h4"))
console.log(document.getElementsByClassName("green"))
console.log(document.getElementById("blue"))
console.log(document.querySelector(".yellow"))
console.log(document.querySelectorAll(".teal"))
